# -*- coding: utf-8 -*-
# Copyright 2023 IZI PT Solusi Usaha Mudah

from odoo import api, fields, models, _
from odoo.exceptions import UserError


class ProductTemplate(models.Model):
    _inherit = 'product.template'

    map_line_ids = fields.One2many(comodel_name="mp.map.product.line", inverse_name="product_tmpl_id",
                                   string="Mapped Lines", readonly=True)
    generated_by_mapping = fields.Boolean(string="Generated by Mapping?", default=False)
    product_map_ref = fields.Char(string="Product Map Ref.", readonly=True)
    mp_product_ids_ref = fields.Char(string="MP Product IDs Ref.", readonly=True)
    mp_account_ids = fields.Many2many('mp.account', string='Marketplace Account', domain=[('default_mp_product', '!=', False)])


    def set_mp_data(self):
        return self.mapped('product_variant_ids').set_mp_data()

    def mp_push_product(self):
        for rec in self:
            if not rec.mp_account_ids:
                raise UserError('Marketplace Account not set.')

            final_result = []
            for mp_account in rec.mp_account_ids:
                if hasattr(mp_account, '%s_upload_product' % mp_account.marketplace):
                    try:
                        result = getattr(mp_account, '%s_upload_product' % mp_account.marketplace)(product_id=rec)
                        final_result.append(result)
                    except Exception as e:
                        raise UserError('[%s] %s' % (mp_account.name, str(e)))

                # then mapping product
                mp_account.mp_map_product_ids[0].action_generate()