# -*- coding: utf-8 -*-

from odoo import models, fields, api, _
from odoo.exceptions import UserError, ValidationError

class Crm_Group(models.Model):
    _inherit = 'crm.lead'
    
    sale_user_group_id = fields.Many2one(
        'sale.user.group',
        string='Sales Person Group',
    )
    
    @api.onchange('partner_id')
    def _onchange_partner_id(self):
        print 'tttttttttttttttttttttttttttttttttttttttttttttttttt',self.partner_id
        print 'tttttttttttttttttttttttttttttttttttttttttttttttttt',self.partner_id.sale_user_group_id
        self.sale_user_group_id = self.partner_id.sale_user_group_id.id
        #res = super(Crm_Group, self)._onchange_partner_id()
        #values = self._onchange_partner_id_values(self.partner_id.sale_user_group_id.id)
        #print 'yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy',values 
        #self.account_analytic_id = rec.analytic_id.id
        res = super(Crm_Group, self)._onchange_partner_id()
        return res
    

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
